name: Test

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        terraform-version: [0.12.15, 0.12.16, 0.12.17, 0.12.18, 0.12.19]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/${{ matrix.terraform-version }}/terraform_${{ matrix.terraform-version }}_linux_amd64.zip
        unzip terraform_${{ matrix.terraform-version }}_linux_amd64.zip
        sudo install -m 755 terraform /usr/local/bin/terraform
    - name: Test with pytest
      run: |
        make test
